namespace ShoppingBasket.Domain
{
    /// <summary>
    /// Voucher to be applied on shopping basket
    /// </summary>
    public class Voucher
    {
        /// <summary>
        /// Gets or sets the code. The code is unique and logic can be maintained in the system or external systems. 
        /// Assuming this to be generated by an external code for the time being.
        /// </summary>
        /// <value>
        /// The code.
        /// </value>
        public string Code { get; set; }

        /// <summary>
        /// Gets or sets the discount cost.
        /// </summary>
        /// <value>
        /// The discount cost.
        /// </value>
        public decimal DiscountCost { get; set; }

        /// <summary>
        /// Gets or sets the reason.
        /// </summary>
        /// <value>
        /// The reason.
        /// </value>
        public string Reason { get; set; }

        /// <summary>
        /// Gets or sets the type of the voucher.
        /// </summary>
        /// <value>
        /// The type of the voucher.
        /// </value>
        public VoucherType VoucherType { get; set; }
    }
}
