//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingBasket.ConsoleApplication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShoppingBasket.ConsoleApplication.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a product Id to add to your cart:.
        /// </summary>
        internal static string AddProductToShoppingCart {
            get {
                return ResourceManager.GetString("AddProductToShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply below voucher codes at the time of checkout.
        /// </summary>
        internal static string ApplyBelowVoucherCodesAtTheTimeOfCheckout {
            get {
                return ResourceManager.GetString("ApplyBelowVoucherCodesAtTheTimeOfCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Quantity:.
        /// </summary>
        internal static string EnterQuantity {
            get {
                return ResourceManager.GetString("EnterQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Voucher code:.
        /// </summary>
        internal static string EnterVoucherCode {
            get {
                return ResourceManager.GetString("EnterVoucherCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InsufficientFunds {
            get {
                return ResourceManager.GetString("InsufficientFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the number displayed in the above list.
        /// </summary>
        internal static string InvalidFormatException {
            get {
                return ResourceManager.GetString("InvalidFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct quantity.
        /// </summary>
        internal static string InvalidQuantity {
            get {
                return ResourceManager.GetString("InvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- £.
        /// </summary>
        internal static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected product doesnt exist in the list.
        /// </summary>
        internal static string ProductDoesnotExist {
            get {
                return ResourceManager.GetString("ProductDoesnotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string ProductIdAndTitleSeparator {
            get {
                return ResourceManager.GetString("ProductIdAndTitleSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products available are:.
        /// </summary>
        internal static string ProductsTitle {
            get {
                return ResourceManager.GetString("ProductsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select another product or enter 0 to checkout or enter X to exit.
        /// </summary>
        internal static string SelectAnotherProduct {
            get {
                return ResourceManager.GetString("SelectAnotherProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Id: {0} Product Name : {1} Quantity : {2} Item Price : {3} Total Price : {4} .
        /// </summary>
        internal static string ShoppingCartItems {
            get {
                return ResourceManager.GetString("ShoppingCartItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your total basket cost without gift vouchers : {0}.
        /// </summary>
        internal static string TotalBasketCostWithoutGiftVouchers {
            get {
                return ResourceManager.GetString("TotalBasketCostWithoutGiftVouchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost after discount: {0}.
        /// </summary>
        internal static string TotalCostAfterDiscount {
            get {
                return ResourceManager.GetString("TotalCostAfterDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string VoucherApplied {
            get {
                return ResourceManager.GetString("VoucherApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code: {0} Applied for: {1}.
        /// </summary>
        internal static string VoucherCodeAndVoucherReason {
            get {
                return ResourceManager.GetString("VoucherCodeAndVoucherReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message : {0}.
        /// </summary>
        internal static string VoucherCodeStatusMessage {
            get {
                return ResourceManager.GetString("VoucherCodeStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered voucher is not valid.
        /// </summary>
        internal static string VoucherNotVallid {
            get {
                return ResourceManager.GetString("VoucherNotVallid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Basket contains:.
        /// </summary>
        internal static string YourBasketContains {
            get {
                return ResourceManager.GetString("YourBasketContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Total Basket Cost : {0}.
        /// </summary>
        internal static string YourTotalBasketCost {
            get {
                return ResourceManager.GetString("YourTotalBasketCost", resourceCulture);
            }
        }
    }
}
